In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
mainpath = "C:/Users/mromo/Desktop/Rappi/Datasets/"
dep1 = {}
dep2 = {}

In [3]:
for x in range(31,35):
    pagos = "S" + str(x) + "/" + "Pagos Vigentes.xlsx"
    pagable = os.path.join(mainpath,pagos)
    pag1 = 'Dep1'
    pag2 = 'Dep2'
    dep1[x] = pd.read_excel(pagable, pag1)
    dep2[x] = pd.read_excel(pagable, pag2)
    print("Carga semana %d ok"%(x))

Carga semana 31 ok
Carga semana 32 ok
Carga semana 33 ok
Carga semana 34 ok

        Estado   SKID  Monto Transferencia
0    PENDIENTE  10042                    0
1    PENDIENTE  10043                    0
2    PENDIENTE  10045                    0
3    PENDIENTE  10046                    0
4       PAGADO  10047               190090
5       PAGADO  10048               208982
6    PENDIENTE  10049                    0
7    PENDIENTE  10050                    0
8    PENDIENTE  10057                    0
9       PAGADO  10059                43995
10      PAGADO  10060                29761
11   PENDIENTE  10061                    0
12   PENDIENTE  10062                    0
13   PENDIENTE  10065                    0
14      PAGADO  10066               103230
15      PAGADO  10067                43356
16   PENDIENTE  10068               187172
17   PENDIENTE  10069                    0
18      PAGADO  10070                40765
19      PAGADO  10071                56858
20      PAGADO  10072                13200
21   PENDIENTE  10073                    0
22   PENDIENTE  10074                    0
23   PENDIENTE  10075                    0
24      PAGADO  10080                44487
25   PENDIENTE  10081                    0
26      PAGADO  10082               105766
27      PAGADO  10083               169014
28   PENDIENTE  10084                    0
29      PAGADO  10085                54185
..         ...    ...                  ...
590  PENDIENTE  11453                    0
591  PENDIENTE  11455                    0
592  PENDIENTE  11460                 8265
593  PENDIENTE  11462                    0
594     PAGADO  11468                12100
595  PENDIENTE  11470                 1655
596  PENDIENTE  11484                    0
597     PAGADO  11485                22136
598  PENDIENTE  11486                    0
599  PENDIENTE  11489                10620
600  PENDIENTE  11490                    0
601  PENDIENTE  11491                    0
602  PENDIENTE  11492                    0
603  PENDIENTE  11493                    0
604  PENDIENTE  11494                55975
605  PENDIENTE  11495                 1807
606  PENDIENTE  11496                    0
607     PAGADO  11497                 5425
608  PENDIENTE  11498                22767
609  PENDIENTE  11502                    0
610  PENDIENTE  11504                    0
611     PAGADO  11505               109113
612     PAGADO  11506               103781
613  PENDIENTE  11508                13417
614  PENDIENTE  11509                    0
615  PENDIENTE  11510                    0
616  PENDIENTE  11514                    0
617  PENDIENTE  11520                    0
618  PENDIENTE  11521                31451
619  PENDIENTE  11522                11167

[620 rows x 3 columns]

In [4]:
for x in range(31,35):
    dep1[x] = dep1[x].loc[:,['Estado','SKID','Monto Transferencia']]
    dep2[x] = dep2[x].loc[:,['Estado','SKID','Monto Transferencia']]

In [5]:
dep1[31].columns.values

array(['Estado', 'SKID', 'Monto Transferencia'], dtype=object)

In [6]:
pagado = pd.DataFrame(columns = dep1[31].columns)
pendiente = pd.DataFrame(columns = dep1[31].columns)
rechazado = pd.DataFrame(columns = dep1[31].columns)

In [7]:
for x in range(31,35):
    pagado = pagado.append(dep1[x].loc[dep1[x]['Estado'] == "PAGADO"])
    pendiente = pendiente.append(dep1[x].loc[dep1[x]['Estado'] == "PENDIENTE"])
    rechazado = rechazado.append(dep1[x].loc[dep1[x]['Estado'] == "RECHAZADO"])

In [8]:
pagado

     Estado   SKID  Monto Transferencia
0    PAGADO  10041              11900.0
1    PAGADO  10045             121650.0
2    PAGADO  10047               2362.0
3    PAGADO  10048             128122.0
4    PAGADO  10049              18800.0
5    PAGADO  10050                  0.0
6    PAGADO  10054               7120.0
7    PAGADO  10059             122261.0
8    PAGADO  10060              59416.0
9    PAGADO  10061               8430.0
10   PAGADO  10064                  0.0
11   PAGADO  10065              83006.0
12   PAGADO  10066             119590.0
13   PAGADO  10067              28971.0
14   PAGADO  10068                  0.0
15   PAGADO  10069               5119.0
16   PAGADO  10070             123369.0
17   PAGADO  10071              14063.0
18   PAGADO  10073                  0.0
19   PAGADO  10075                  0.0
20   PAGADO  10076              30100.0
21   PAGADO  10079              14200.0
22   PAGADO  10080             110300.0
23   PAGADO  10081                  0.0
24   PAGADO  10082              42706.0
25   PAGADO  10083             146428.0
26   PAGADO  10084                  0.0
27   PAGADO  10085                  0.0
28   PAGADO  10086              20400.0
29   PAGADO  10087               7000.0
..      ...    ...                  ...
519  PAGADO  11234              65337.0
520  PAGADO  11235              22200.0
522  PAGADO  11237             137191.0
523  PAGADO  11241             323140.0
524  PAGADO  11243             110524.0
525  PAGADO  11244              26297.0
526  PAGADO  11245               3749.0
527  PAGADO  11248             138334.0
529  PAGADO  11295              52952.0
530  PAGADO  11296               9300.0
531  PAGADO  11301              25981.0
536  PAGADO  11351              33257.0
537  PAGADO  11363              11762.0
540  PAGADO  11368              66527.0
543  PAGADO  11372              23046.0
548  PAGADO  11382              16679.0
550  PAGADO  11387              66677.0
554  PAGADO  11394              27350.0
555  PAGADO  11395               9650.0
557  PAGADO  11397              45122.0
559  PAGADO  11406              22201.0
563  PAGADO  11410              53885.0
565  PAGADO  11412              14240.0
575  PAGADO  11427               9970.0
580  PAGADO  11441              23482.0
594  PAGADO  11468              12100.0
597  PAGADO  11485              22136.0
607  PAGADO  11497               5425.0
611  PAGADO  11505             109113.0
612  PAGADO  11506             103781.0

[1486 rows x 3 columns]

In [9]:
pagado = pagado.groupby(['SKID','Estado']).sum().reset_index()
pagado

        SKID  Estado  Monto Transferencia
0    10041.0  PAGADO              11900.0
1    10042.0  PAGADO                  0.0
2    10045.0  PAGADO             211654.0
3    10047.0  PAGADO             314086.0
4    10048.0  PAGADO             580591.0
5    10049.0  PAGADO              18800.0
6    10050.0  PAGADO                  0.0
7    10054.0  PAGADO               7120.0
8    10059.0  PAGADO             304524.0
9    10060.0  PAGADO             128781.0
10   10061.0  PAGADO               8430.0
11   10064.0  PAGADO              56370.0
12   10065.0  PAGADO             186874.0
13   10066.0  PAGADO             361085.0
14   10067.0  PAGADO             196200.0
15   10068.0  PAGADO                  0.0
16   10069.0  PAGADO             111361.0
17   10070.0  PAGADO             198828.0
18   10071.0  PAGADO              70921.0
19   10072.0  PAGADO              13200.0
20   10073.0  PAGADO                  0.0
21   10074.0  PAGADO                  0.0
22   10075.0  PAGADO              19000.0
23   10076.0  PAGADO              34800.0
24   10079.0  PAGADO              44950.0
25   10080.0  PAGADO             291106.0
26   10081.0  PAGADO                  0.0
27   10082.0  PAGADO             241919.0
28   10083.0  PAGADO             315442.0
29   10084.0  PAGADO                  0.0
..       ...     ...                  ...
536  11245.0  PAGADO               3749.0
537  11248.0  PAGADO             242375.0
538  11261.0  PAGADO                  0.0
539  11262.0  PAGADO                  0.0
540  11267.0  PAGADO             185237.0
541  11295.0  PAGADO              52952.0
542  11296.0  PAGADO               9300.0
543  11301.0  PAGADO              25981.0
544  11318.0  PAGADO                  0.0
545  11332.0  PAGADO                  0.0
546  11334.0  PAGADO                  0.0
547  11351.0  PAGADO              33257.0
548  11363.0  PAGADO              11762.0
549  11368.0  PAGADO              66527.0
550  11372.0  PAGADO              23046.0
551  11382.0  PAGADO              16679.0
552  11387.0  PAGADO              66677.0
553  11394.0  PAGADO              27350.0
554  11395.0  PAGADO               9650.0
555  11397.0  PAGADO              45122.0
556  11406.0  PAGADO              22201.0
557  11410.0  PAGADO              53885.0
558  11412.0  PAGADO              14240.0
559  11427.0  PAGADO               9970.0
560  11441.0  PAGADO              23482.0
561  11468.0  PAGADO              12100.0
562  11485.0  PAGADO              22136.0
563  11497.0  PAGADO               5425.0
564  11505.0  PAGADO             109113.0
565  11506.0  PAGADO             103781.0

[566 rows x 3 columns]

In [10]:
pagado.dtypes

SKID                   float64
Estado                  object
Monto Transferencia    float64
dtype: object

In [11]:
pendiente = pendiente.groupby(['SKID','Estado']).sum().reset_index()

In [12]:
pendiente.dtypes

SKID                   float64
Estado                  object
Monto Transferencia    float64
dtype: object

In [13]:
rechazado = rechazado.groupby(['SKID','Estado']).sum().reset_index()

In [14]:
rechazado

    SKID     Estado  Monto Transferencia
0  10326  RECHAZADO              29708.0
1  10327  RECHAZADO              53325.0
2  10785  RECHAZADO              43869.0
3  11047  RECHAZADO              16082.0

In [15]:
consolidado = pd.merge(pagado,pendiente, how ='outer', on=['SKID'])
consolidado.dtypes

SKID                     float64
Estado_x                  object
Monto Transferencia_x    float64
Estado_y                  object
Monto Transferencia_y    float64
dtype: object

In [16]:
consolidado = pd.merge(consolidado, rechazado, how='left', on=['SKID'])

In [17]:
consolidado.fillna('')

,SKID,Estado_x,Monto Transferencia_x,Estado_y,Monto Transferencia_y,Estado,Monto Transferencia
0,10041.0,PAGADO,11900,,,,
1,10042.0,PAGADO,0,PENDIENTE,0,,
2,10045.0,PAGADO,211654,PENDIENTE,0,,
3,10047.0,PAGADO,314086,,,,
4,10048.0,PAGADO,580591,,,,
5,10049.0,PAGADO,18800,PENDIENTE,0,,
6,10050.0,PAGADO,0,PENDIENTE,0,,
7,10054.0,PAGADO,7120,,,,
8,10059.0,PAGADO,304524,,,,
9,10060.0,PAGADO,128781,,,,
10,10061.0,PAGADO,8430,PENDIENTE,0,,
11,10064.0,PAGADO,56370,,,,
12,10065.0,PAGADO,186874,PENDIENTE,0,,
13,10066.0,PAGADO,361085,,,,
14,10067.0,PAGADO,196200,,,,
15,10068.0,PAGADO,0,PENDIENTE,187172,,
16,10069.0,PAGADO,111361,PENDIENTE,0,,
17,10070.0,PAGADO,198828,,,,
18,10071.0,PAGADO,70921,,,,
19,10072.0,PAGADO,13200,,,,
20,10073.0,PAGADO,0,PENDIENTE,0,,
21,10074.0,PAGADO,0,PENDIENTE,0,,
22,10075.0,PAGADO,19000,PENDIENTE,0,,
23,10076.0,PAGADO,34800,,,,
24,10079.0,PAGADO,44950,,,,
25,10080.0,PAGADO,291106,,,,
26,10081.0,PAGADO,0,PENDIENTE,0,,
27,10082.0,PAGADO,241919,,,,
28,10083.0,PAGADO,315442,PENDIENTE,140471,,
29,10084.0,PAGADO,0,PENDIENTE,0,,
...,...,...,...,...,...,...,...
668,11446.0,,,PENDIENTE,5677,,
669,11447.0,,,PENDIENTE,0,,
670,11449.0,,,PENDIENTE,0,,
671,11451.0,,,PENDIENTE,0,,
672,11452.0,,,PENDIENTE,11510,,
673,11453.0,,,PENDIENTE,0,,
674,11455.0,,,PENDIENTE,0,,
675,11460.0,,,PENDIENTE,8265,,
676,11462.0,,,PENDIENTE,0,,
677,11470.0,,,PENDIENTE,1655,,
678,11484.0,,,PENDIENTE,0,,
679,11486.0,,,PENDIENTE,0,,
680,11489.0,,,PENDIENTE,10620,,
681,11490.0,,,PENDIENTE,0,,
682,11491.0,,,PENDIENTE,0,,
683,11492.0,,,PENDIENTE,0,,
684,11493.0,,,PENDIENTE,0,,
685,11494.0,,,PENDIENTE,55975,,
686,11495.0,,,PENDIENTE,1807,,
687,11496.0,,,PENDIENTE,0,,
688,11498.0,,,PENDIENTE,22767,,
689,11502.0,,,PENDIENTE,0,,
690,11504.0,,,PENDIENTE,0,,
691,11508.0,,,PENDIENTE,13417,,
692,11509.0,,,PENDIENTE,0,,
693,11510.0,,,PENDIENTE,0,,
694,11514.0,,,PENDIENTE,0,,
695,11520.0,,,PENDIENTE,0,,
696,11521.0,,,PENDIENTE,31451,,
697,11522.0,,,PENDIENTE,11167,,

In [18]:
consolidado = consolidado.sort_values('SKID')

In [19]:
consolidado[consolidado['Estado']=='RECHAZADO']

,SKID,Estado_x,Monto Transferencia_x,Estado_y,Monto Transferencia_y,Estado,Monto Transferencia
86,10326.0,PAGADO,126622.0,NaN,NaN,RECHAZADO,29708.0
87,10327.0,PAGADO,102880.0,NaN,NaN,RECHAZADO,53325.0
314,10785.0,PAGADO,314690.0,PENDIENTE,88329.0,RECHAZADO,43869.0
476,11047.0,PAGADO,32804.0,PENDIENTE,107816.0,RECHAZADO,16082.0

In [20]:
semana = str(x+1)
consolidado.to_excel(mainpath + "/" + "Consolidado Por RT a S"+ semana + ".xlsx")